package hotel;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import menu.Frame_AcercaDe;
import menu.Frame_Estancia;
import menu.Frame_Mobiliario;
import menu.Frame_Usuarios;
import menu.Frame_habitaciones;
import menu.Frame_habitaciones_mobiliario;
import menu.Frame_nueva_estancia;

public class Frame_Menu extends javax.swing.JFrame {
     Connection con = null;
     Inicio_sesion_Frame f;
     menu.Frame_Estancia fe;
     GradientPaint horizontalGradient;
     Graphics2D g2d;
    /**
     * Creates new form Frame_principal_administrador
     */
    public Frame_Menu() {
        initComponents();
    }
    
    public Frame_Menu(Connection _con , Inicio_sesion_Frame _f) {            
        initComponents();
        con=_con;
        f=_f;
        f.verificarSalida();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Emojin.png"));
        return  retValue;
    }
    @Override
 public void paint(Graphics g) {
  g2d = (Graphics2D) g;
  horizontalGradient = new GradientPaint(0, 0, new Color(61, 91, 178) ,0, getHeight(),Color.lightGray);
  g2d.setPaint(horizontalGradient);
  g2d.fillRect(0, 0, getWidth(), getHeight());
  jlbltipo.repaint();
  jbtnUsuarios.repaint();
  jbtnHabitaciones.repaint();
  jbtnMobiliario.repaint();
  jbtnrelacion.repaint();
  jbtnEstancia.repaint();
  jbtnNuevaEstancia.repaint();
  jButton1.repaint();
  jbtnCerrarSesion.repaint();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCerrarSesion = new javax.swing.JButton();
        jbtnUsuarios = new javax.swing.JButton();
        jbtnHabitaciones = new javax.swing.JButton();
        jbtnEstancia = new javax.swing.JButton();
        jbtnMobiliario = new javax.swing.JButton();
        jbtnrelacion = new javax.swing.JButton();
        jbtnNuevaEstancia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jlbltipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú del Hotel");
        setIconImage(getIconImage());

        jbtnCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonCerrarSesion.jpg"))); // NOI18N
        jbtnCerrarSesion.setText("Cerrar Sesion");
        jbtnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarSesionActionPerformed(evt);
            }
        });

        jbtnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarioBoton.png"))); // NOI18N
        jbtnUsuarios.setText("Usuarios");
        jbtnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuariosActionPerformed(evt);
            }
        });

        jbtnHabitaciones.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonHabitaciones.jpg"))); // NOI18N
        jbtnHabitaciones.setText("Habitacion");
        jbtnHabitaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnHabitaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHabitacionesActionPerformed(evt);
            }
        });

        jbtnEstancia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnEstancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonEstancia.jpg"))); // NOI18N
        jbtnEstancia.setText("Estancias");
        jbtnEstancia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEstancia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnEstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEstanciaActionPerformed(evt);
            }
        });

        jbtnMobiliario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnMobiliario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonMobiliario.jpg"))); // NOI18N
        jbtnMobiliario.setText("Mobiliario");
        jbtnMobiliario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMobiliario.setName(""); // NOI18N
        jbtnMobiliario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnMobiliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMobiliarioActionPerformed(evt);
            }
        });

        jbtnrelacion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnrelacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonRelacion.jpg"))); // NOI18N
        jbtnrelacion.setText("Relacion");
        jbtnrelacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnrelacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnrelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrelacionActionPerformed(evt);
            }
        });

        jbtnNuevaEstancia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnNuevaEstancia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonNuevaEstancia.png"))); // NOI18N
        jbtnNuevaEstancia.setText("Nueva Estancia");
        jbtnNuevaEstancia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnNuevaEstancia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnNuevaEstancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevaEstanciaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AcercadeBoton.jpg"))); // NOI18N
        jButton1.setText("Acerca de");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlbltipo.setBackground(new java.awt.Color(61, 103, 177));
        jlbltipo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlbltipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbltipo.setText("Administrador");
        jlbltipo.setOpaque(true);

        jLabel8.setText("                              ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtnMobiliario)
                                .addComponent(jButton1))
                            .addComponent(jbtnEstancia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnUsuarios)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbtnCerrarSesion)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnNuevaEstancia))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbtnHabitaciones)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnrelacion)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlbltipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbltipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnMobiliario, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jbtnHabitaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnrelacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnNuevaEstancia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionActionPerformed
    try {
            String sql = "call fin_sesion('"+f.cadena+"')";
            Statement ps = con.createStatement();
             ps.executeUpdate(sql);
             ps.close();      
             
        } catch (Exception e) {
            System.out.println("ERROR:" + e);
        }    
        
        
        Inicio_sesion_Frame icf = new Inicio_sesion_Frame();
            icf.setLocationRelativeTo(null);
            icf.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jbtnCerrarSesionActionPerformed

    private void jbtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuariosActionPerformed
     menu.Frame_Usuarios fu = new Frame_Usuarios(con ,f,this);
     fu.setLocationRelativeTo(null);
     fu.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jbtnUsuariosActionPerformed

    private void jbtnMobiliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMobiliarioActionPerformed
    menu.Frame_Mobiliario fm = new Frame_Mobiliario(con, f, this);
    fm.setLocationRelativeTo(null);
    fm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jbtnMobiliarioActionPerformed

    private void jbtnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHabitacionesActionPerformed
        menu.Frame_habitaciones fh = new Frame_habitaciones(con, f , this);
        fh.setLocationRelativeTo(null);
        fh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnHabitacionesActionPerformed

    private void jbtnrelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrelacionActionPerformed
         menu.Frame_habitaciones_mobiliario fhm = new Frame_habitaciones_mobiliario(con, f , this);
        fhm.setLocationRelativeTo(null);
        fhm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnrelacionActionPerformed

    private void jbtnEstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEstanciaActionPerformed
        fe = new Frame_Estancia(con, f , this);
        fe.setLocationRelativeTo(null);
        fe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnEstanciaActionPerformed

    private void jbtnNuevaEstanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevaEstanciaActionPerformed
        menu.Frame_nueva_estancia fne = new Frame_nueva_estancia(con, f,this ,  fe);
        fne.setLocationRelativeTo(null);
        fne.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNuevaEstanciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menu.Frame_AcercaDe a = new Frame_AcercaDe();
        a.setVisible(true);
        a.setResizable(false);
        a.setLocationRelativeTo(null);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JButton jbtnCerrarSesion;
    public javax.swing.JButton jbtnEstancia;
    public javax.swing.JButton jbtnHabitaciones;
    public javax.swing.JButton jbtnMobiliario;
    public javax.swing.JButton jbtnNuevaEstancia;
    public javax.swing.JButton jbtnUsuarios;
    public javax.swing.JButton jbtnrelacion;
    public javax.swing.JLabel jlbltipo;
    // End of variables declaration//GEN-END:variables
}
