
package hotel;

import java.awt.Image;
import java.awt.Toolkit;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class Inicio_sesion_Frame extends javax.swing.JFrame {
    Connection con = null;
    final String STRING_CONEXION = "jdbc:mysql://localhost:3306/hotel?useUnicode=true&useJDBCCompliantTimezoneShif=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull";
    String usuario = "";
    String pwd = "";
    public String cadena;
    public int ses_id;
    /**
     * Creates new form Inicio_sesion_Frame
     */
    public Inicio_sesion_Frame() {
        initComponents();
        
        setSize(480, 640);
        labelFonfo.setSize(480, 640);
        
        setResizable(false);
        setTitle("Acceso al sistema");
        setLocationRelativeTo(null);

        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(labelFonfo.getWidth(),
                labelFonfo.getHeight(), Image.SCALE_DEFAULT));
        labelFonfo.setIcon(icono);
        this.repaint();
        
        ImageIcon empresa = new ImageIcon("src/imagenes/Empresa.png");
        Icon iconoE = new ImageIcon(empresa.getImage().getScaledInstance(labelEmpesa.getWidth(),
                labelEmpesa.getHeight(), Image.SCALE_DEFAULT));
        labelEmpesa.setIcon(iconoE);
        this.repaint();
        
        Conectar();
        verificarSalida();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Emojin.png"));
        return  retValue;
    }
    
        //metodo para verificar la salida de la app    
    public void verificarSalida(){   
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
 
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "Salir del sistema", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    actulizar_sesion();
            System.exit(0);}
        else{
        Conectar();}
            }
        });}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxfUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnIniciar = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jpwfdContraseña = new javax.swing.JPasswordField();
        labelEmpesa = new javax.swing.JLabel();
        labelFonfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfUsuario.setBackground(new java.awt.Color(102, 153, 255));
        jtxfUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jtxfUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jtxfUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxfUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 210, 30));

        jLabel1.setFont(new java.awt.Font("Century", 1, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOTELES MAKUMBA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jbtnIniciar.setBackground(new java.awt.Color(0, 153, 0));
        jbtnIniciar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnIniciar.setText("Iniciar Sesion");
        jbtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 210, 40));

        jbtnSalir.setBackground(new java.awt.Color(255, 51, 51));
        jbtnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 110, 50));

        jpwfdContraseña.setBackground(new java.awt.Color(102, 153, 255));
        jpwfdContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jpwfdContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpwfdContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpwfdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwfdContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jpwfdContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 210, 30));
        getContentPane().add(labelEmpesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 274, 244));
        getContentPane().add(labelFonfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        Desconectar();
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarActionPerformed
        
        if (!jtxfUsuario.getText().trim().equals("") && !jpwfdContraseña.getText().trim().equals("")) {
        int usr_id=0;
        String sql;
        ResultSet rs;
        String ip="";
        String so;
        String tipo="";
        PreparedStatement ps; 
            usuario = jtxfUsuario.getText();
            pwd = jpwfdContraseña.getText();            
            Conectar();
            try {
            sql = "SELECT usr_id('"+usuario+"','"+pwd+"');";
            ps = con.prepareStatement( sql );
            rs = ps.executeQuery();
            if(rs.next())
                usr_id = rs.getInt(1);    
            if(usr_id!=0){ 
                
            sql = "SELECT tipo_usuario('"+usuario+"','"+pwd+"');";
            ps = con.prepareStatement( sql );
            rs = ps.executeQuery();
            if(rs.next())
                tipo = rs.getString(1);
                    
            cadena = UUID.randomUUID().toString().substring(0, 8);
            so = System.getProperty("os.name");
            try {
                ip = InetAddress.getLocalHost().getHostAddress();
            } catch (UnknownHostException ex) {System.out.println(""+ex);}
            
            
                  
            sql = "call nueva_sesion('"+cadena+"','"+ip+"','"+so+"','"+usuario+"')";
            Statement pss = con.createStatement();
             pss.executeUpdate(sql);
             
            sql = "SELECT ses_id('"+cadena+"');";
            ps = con.prepareStatement( sql );
            rs = ps.executeQuery();
            if(rs.next())
                ses_id = rs.getInt(1);
             
             pss.close();
             ps.close();
             rs.close();
            
           
            Frame_Menu fpa;
            switch(tipo){
                case "Administrador":
                    fpa = new Frame_Menu(con , this);
                    fpa.setLocationRelativeTo(null);                    
                    fpa.jlbltipo.setText("Administador: "+usuario);
                    this.dispose();
                    fpa.setVisible(true);
                    fpa.setSize(490, 740);
                    
                break;
                case "Moderador":
                    fpa = new Frame_Menu(con ,this );
                    fpa.setLocationRelativeTo(null); 
                    
                    
                    fpa.jlbltipo.setText("Moderador: "+ usuario);
                    fpa.jbtnUsuarios.setVisible(false);
                    this.dispose();
                    fpa.setVisible(true);
                    fpa.jlbltipo.setLocation(30, 90);
                    fpa.setSize(490, 610);
                    
                break;  
                case "Normal":
                    fpa = new Frame_Menu(con , this);
                    fpa.setLocationRelativeTo(null); 
                    fpa.jbtnrelacion.setVisible(false);                  
                    fpa.jlbltipo.setText("Trabajador: "+usuario);
                    fpa.jbtnUsuarios.setVisible(false);
                    fpa.jbtnMobiliario.setVisible(false);
                    fpa.jbtnHabitaciones.setVisible(false);                   
                    this.dispose();
                    fpa.setVisible(true);
                    fpa.setSize(440, 420);
                break;    
            }  
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "La contraseña y el usuario. No coinciden!",
                    " Usuario Invalido", JOptionPane.INFORMATION_MESSAGE);}
            }catch (SQLException ex) {System.out.println(""+ex);}
        } else {
            JOptionPane.showMessageDialog(this,
                    "Se necesitan llenar todos los campos",
                    "  Campos vacios", HEIGHT);
        }
                
        
    }//GEN-LAST:event_jbtnIniciarActionPerformed

    private void jpwfdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwfdContraseñaActionPerformed
        jbtnIniciarActionPerformed(evt);
    }//GEN-LAST:event_jpwfdContraseñaActionPerformed
/*------------------------------------------------------------------------------------------*/
//metodo conectar    
    private void Conectar() {   
    
        try {

            con = DriverManager.getConnection(STRING_CONEXION, "adm_hotel" ,"administrador" );
        } catch (SQLException ex) {
            Logger.getLogger(Inicio_sesion_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
            

        }
/*------------------------------------------------------------------------------------------*/
//metodo deconectar
    private void Desconectar(){
        if (con != null) {
            try {
                con.close();
            } catch (SQLException ex) {
                System.out.println("Error al cerrar; " + ex);
            }
            con = null;
            
        }
    }
    
  public void actulizar_sesion(){
  try {
            String sql = "call actualizar_sesion('"+cadena+"')";
            Statement ps = con.createStatement();
             ps.executeUpdate(sql);
             ps.close();      
             
        } catch (Exception e) {
            System.out.println("ERROR:" + e);
        }    
  }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_sesion_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_sesion_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnIniciar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JPasswordField jpwfdContraseña;
    private javax.swing.JTextField jtxfUsuario;
    private javax.swing.JLabel labelEmpesa;
    private javax.swing.JLabel labelFonfo;
    // End of variables declaration//GEN-END:variables
}
