
package hotel;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;
/**
 *
 * @author ebelm
 */
public class SplashFrame extends javax.swing.JFrame {

    private ActionListener al;
    private Timer t;
/*constructor del frame Splash , con un timer para poder llenar la progress bar 
    y al finalizar cerrar y abrir el prisma frame */
    public SplashFrame() {
        initComponents();
        UIManager.put("nimbusOrange", new Color(0, 161, 44));
        al = new ActionListener(){
            @Override
            public void actionPerformed (ActionEvent ev){
                if(jProgressBar1.getValue () < 100 ){
                   
                    jProgressBar1.setValue(jProgressBar1.getValue() + 4 );
                } 
                else{
                    t.stop();
                    mostrarVentana ();
                }
            }
        };
        
        AWTUtilities.setWindowOpaque(this, false );        
        setSize(486,275);
        setLocationRelativeTo(null);
         t = new Timer(80,al);
         t.start();
        
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Emojin.png"));
        return  retValue;
    }
    
  public void mostrarVentana(){
  Inicio_sesion_Frame p = new Inicio_sesion_Frame();
  p.setLocationRelativeTo(null);
  p.setVisible ( true );
  this.dispose ();
  }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(null);

        jProgressBar1.setBackground(new java.awt.Color(0, 161, 44));
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(144, 19));
        jProgressBar1.setString("Cargando..");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(0, 250, 490, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/casco.gif"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 490, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

}