/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ebelm
 */
public class Frame_nueva_estancia extends javax.swing.JFrame {
    Connection con;
    hotel.Inicio_sesion_Frame f;
    hotel.Frame_Menu fm;
    Frame_Estancia fe;
    int indice ;
    String tipo;
    /**
     * Creates new form Frame_nueva_estancia
     */
    public Frame_nueva_estancia() {
        initComponents();
    }
    
    
    
    public Frame_nueva_estancia(Connection _con , hotel.Inicio_sesion_Frame _f,hotel.Frame_Menu _fm, Frame_Estancia _fe) {
        initComponents();
        con=_con;
        f=_f;
        fm=_fm;
        fe=_fe;
        Actualizarboxdias();
        Actualizarboxhabitaciones();
        indice = 0;
        jcbxDisponibles.setVisible(false);
        jLabel6.setVisible(false);  
        jbtnAgregar.setVisible(false);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(labelFonfo.getWidth(),
                labelFonfo.getHeight(), Image.SCALE_DEFAULT));
        labelFonfo.setIcon(icono);
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Emojin.png"));
        return  retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxfnombre = new javax.swing.JTextField();
        jtxfapellido = new javax.swing.JTextField();
        jcbxDias = new javax.swing.JComboBox<>();
        jcbxTipo = new javax.swing.JComboBox<>();
        jbtnAgregar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        jbtnCosultar = new javax.swing.JButton();
        jcbxDisponibles = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnbuscar = new javax.swing.JButton();
        labelFonfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar Estancia");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfnombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jtxfnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, -1));

        jtxfapellido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jtxfapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 170, -1));

        jcbxDias.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jcbxTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, 30));

        jbtnAgregar.setBackground(new java.awt.Color(51, 153, 0));
        jbtnAgregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 110, 30));

        jbtnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        jbtnCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 110, 30));

        jbtnCosultar.setBackground(new java.awt.Color(153, 255, 255));
        jbtnCosultar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnCosultar.setText("Consultar precio");
        jbtnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCosultarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCosultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 30));

        jcbxDisponibles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcbxDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbxDisponibles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbxDisponiblesItemStateChanged(evt);
            }
        });
        getContentPane().add(jcbxDisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 30));

        jLabel2.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nueva Estancia");
        jLabel2.setToolTipText("titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 170, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Dias:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Tipo Habitacion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Disponibles:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        jbtnbuscar.setBackground(new java.awt.Color(153, 255, 255));
        jbtnbuscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnbuscar.setText("Buscar Disponibles");
        jbtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, 30));

        labelFonfo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(labelFonfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscarActionPerformed
     tipo = jcbxTipo.getSelectedItem().toString();
    Actualizarboxdisponibles();
    jcbxDisponibles.setVisible(true);
    jLabel6.setVisible(true);
    }//GEN-LAST:event_jbtnbuscarActionPerformed

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
      if(!jtxfnombre.getText().trim().equals("")&&!jtxfapellido.getText().trim().equals("")){
        String nombre =jtxfnombre.getText();
       String apellido = jtxfapellido.getText();
       int id_hab = Integer.parseInt(jcbxDisponibles.getSelectedItem().toString());
       int dias = Integer.parseInt( jcbxDias.getSelectedItem().toString());
        try {
            String sql = "call registrar_estancia('"+nombre+"','"+apellido+"',"+dias+","+id_hab+")";
            Statement ps = con.createStatement();
            ps.executeUpdate(sql);
            ps.close();

        } catch (Exception e) {
            System.out.println( e );
        }
        f.actulizar_sesion();
        fe = new Frame_Estancia(con, f, fm);
        fe.setLocationRelativeTo(null);
        fe.Actualizartabla();
        fe.Actualizarboxhabitaciones();
        fe.setVisible(true);
        this.dispose();
      }
      else{
        JOptionPane.showMessageDialog(this,
                    "Se necesitan llenar todos los campos",
                    "  Campos vacios", HEIGHT);
        }
    }//GEN-LAST:event_jbtnAgregarActionPerformed

    private void jbtnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCosultarActionPerformed
        String tipo_hab = jcbxTipo.getSelectedItem().toString();
       int dias = Integer.parseInt( jcbxDias.getSelectedItem().toString());
       int precio=0;
        try {
            String sql = "SELECT consultar_precio('"+tipo_hab+"',"+dias+")";
            PreparedStatement ps = con.prepareStatement( sql );
            ResultSet rs = ps.executeQuery();
            if(rs.next())
                 precio = rs.getInt(1);
            JOptionPane.showMessageDialog(this,"El precio es: $"+precio+". total","Cosultar Precio", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println( e );
        }
        f.actulizar_sesion();
    }//GEN-LAST:event_jbtnCosultarActionPerformed

    private void jcbxDisponiblesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbxDisponiblesItemStateChanged
       jbtnAgregar.setVisible(true);
    }//GEN-LAST:event_jcbxDisponiblesItemStateChanged
    public  void Actualizarboxdisponibles(){
        
        try {       
        
        String sql = "SELECT hab_codigo FROM habitacion AS hab\n" +
"LEFT JOIN tipo_habitacion AS thab ON (hab.tip_hab_codigo = thab.tip_hab_codigo)\n" +
"WHERE (thab.tip_hab_descripcion like '"+tipo+"') AND (hab.hab_disponible like 'disponible');";
        PreparedStatement ps = con.prepareStatement( sql );
        ResultSet rs = ps.executeQuery();
        jcbxDisponibles.removeAllItems();
        while (rs.next()){
                int codigo      = rs.getInt(1 );       
        jcbxDisponibles.addItem(Integer.toString( codigo));
        }
            
    } catch (Exception ex) {System.out.println(""+ex);}
    }
    public  void Actualizarboxhabitaciones(){
        try {       
        String sql = "SELECT tip_hab_descripcion FROM tipo_habitacion";
        PreparedStatement ps = con.prepareStatement( sql );
        ResultSet rs = ps.executeQuery();
        jcbxTipo.removeAllItems();
        while (rs.next()){
                String nombre      = rs.getString     ( 1 );       
        jcbxTipo.addItem(nombre);
        } 
    } catch (Exception ex) {System.out.println(""+ex);}
    }
    public  void Actualizarboxdias(){
         jcbxDias.removeAllItems();
         for (int i = 0; i < 40; i++) {
             jcbxDias.addItem(Integer.toString(i+1));
         }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_nueva_estancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_nueva_estancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_nueva_estancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_nueva_estancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_nueva_estancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCosultar;
    private javax.swing.JButton jbtnbuscar;
    private javax.swing.JComboBox<String> jcbxDias;
    private javax.swing.JComboBox<String> jcbxDisponibles;
    private javax.swing.JComboBox<String> jcbxTipo;
    private javax.swing.JTextField jtxfapellido;
    private javax.swing.JTextField jtxfnombre;
    private javax.swing.JLabel labelFonfo;
    // End of variables declaration//GEN-END:variables
}
