/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ebelm
 */
public class Frame_Mobiliario extends javax.swing.JFrame {
    Connection con = null;
    hotel.Inicio_sesion_Frame f;
    hotel.Frame_Menu fm;
    int select_row =0;
    int id_select =0;
    int precio_select ;
    String nombre_select ;
    
    Vector columnas = new Vector();
    Vector fila     = new Vector();
    Vector datos    = new Vector();
    DefaultTableModel    modelo;
    /**
     * Creates new form Frame_Mobiliario
     */
    public Frame_Mobiliario() {
        initComponents();
    }
    public Frame_Mobiliario(Connection _con , hotel.Inicio_sesion_Frame _f,hotel.Frame_Menu _fm) {
        initComponents();
        con=_con;
        f=_f;
        fm=_fm;
        columnas.add( "ID" );
        columnas.add( "Nombre" );
        columnas.add( "Precio" );
        Actualizartabla();
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jtxfprecio.setVisible(false);
        jtxfNombre.setVisible(false);
        jbtnActualizar.setVisible(false);
        jbtnAgregar.setVisible(false);
        
        ImageIcon wallpaper = new ImageIcon("src/imagenes/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(labelFonfo.getWidth(),
                labelFonfo.getHeight(), Image.SCALE_DEFAULT));
        labelFonfo.setIcon(icono);
        this.repaint();
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Emojin.png"));
        return  retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxfNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnActualizar = new javax.swing.JButton();
        jbtnRegistrar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jbtnRegresar = new javax.swing.JButton();
        jtxfprecio = new javax.swing.JTextField();
        jbtnAgregar = new javax.swing.JButton();
        labelFonfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mobiliario");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxfNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jtxfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 325, 100, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 296, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 296, -1, -1));

        jbtnActualizar.setBackground(new java.awt.Color(153, 255, 255));
        jbtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnActualizar.setText("Actualizar");
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 110, 30));

        jbtnRegistrar.setBackground(new java.awt.Color(51, 153, 0));
        jbtnRegistrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrar.setText("Registrar");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jbtnModificar.setBackground(new java.awt.Color(102, 153, 255));
        jbtnModificar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnModificar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        jbtnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        jbtnEliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 110, 30));

        jtableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableUsuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, 164));

        jLabel2.setFont(new java.awt.Font("Century", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobiliario");
        jLabel2.setToolTipText("titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jbtnRegresar.setBackground(new java.awt.Color(255, 102, 102));
        jbtnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegresar.setText("Regresar");
        jbtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 110, 30));

        jtxfprecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jtxfprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 325, 101, -1));

        jbtnAgregar.setBackground(new java.awt.Color(51, 153, 0));
        jbtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregar.setText("Agregar");
        jbtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 110, 30));
        getContentPane().add(labelFonfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed

        String nombre = jtxfNombre.getText();
        String precio = jtxfprecio.getText();
        try {
            String sql = "call actualizar_mobiliario('"+nombre+"',"+precio+","+id_select+")";
            Statement ps = con.createStatement();
            ps.executeUpdate(sql);
            ps.close();

        } catch (Exception e) {
            System.out.println( e );
        }
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jtxfprecio.setText("");
        jtxfprecio.setVisible(false);
        jtxfNombre.setText("");
        jtxfNombre.setVisible(false);
        jbtnActualizar.setVisible(false);
        Actualizartabla();
        f.actulizar_sesion();

    }//GEN-LAST:event_jbtnActualizarActionPerformed

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
            jLabel1.setVisible(true);
            jLabel3.setVisible(true);
            jtxfprecio.setVisible(true);
            jtxfNombre.setVisible(true);
            jbtnAgregar.setVisible(true);
            jbtnActualizar.setVisible(false);
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed

        if(id_select!=0)
        {
            jLabel1.setVisible(true);
            jLabel3.setVisible(true);
            jtxfprecio.setVisible(true);
            jtxfNombre.setVisible(true);
            jbtnActualizar.setVisible(true);
            jbtnAgregar.setVisible(false);
            jtxfNombre.setText(nombre_select);
            jtxfprecio.setText(Integer.toString(precio_select));
        }
        else{
            JOptionPane.showMessageDialog(this,"No has seleccionado un mobiliario para modificar","No seleccion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        if(id_select!=0)
        {
            try {
                String sql = "call eliminar_mobiliario("+id_select+")";
                Statement ps = con.createStatement();
                ps.executeUpdate(sql);
                ps.close();
                f.actulizar_sesion();
            } catch (Exception e) {
                System.out.println( e );
            }
            Actualizartabla();

        }
        else{
            JOptionPane.showMessageDialog(this,"No has seleccionado un Mobiliario para Eliminar","No seleccion", JOptionPane.INFORMATION_MESSAGE);
        }
        select_row=0;
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jtableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableUsuariosMouseClicked
        select_row = jtableUsuarios.getSelectedRow();
        id_select = Integer.parseInt(jtableUsuarios.getValueAt(select_row, 0).toString());
        nombre_select = jtableUsuarios.getValueAt(select_row, 1).toString();
        precio_select = Integer.parseInt(jtableUsuarios.getValueAt(select_row, 2).toString());
    }//GEN-LAST:event_jtableUsuariosMouseClicked

    private void jbtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegresarActionPerformed
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnRegresarActionPerformed

    private void jbtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarActionPerformed
      if(!jtxfNombre.getText().trim().equals("")&&!jtxfprecio.getText().trim().equals("")){
        String nombre = jtxfNombre.getText();
        String precio = jtxfprecio.getText();
        try {
            String sql = "call registrar_mobiliario('"+nombre+"',"+precio+")";
            Statement ps = con.createStatement();
            ps.executeUpdate(sql);
            ps.close();

        } catch (Exception e) {
            System.out.println( e );
        }
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jtxfprecio.setText("");
        jtxfprecio.setVisible(false);
        jtxfNombre.setText("");
        jtxfNombre.setVisible(false);
        jbtnAgregar.setVisible(false);
        Actualizartabla();
        f.actulizar_sesion();}
      else{
      JOptionPane.showMessageDialog(this,
                    "Se necesitan llenar todos los campos",
                    "  Campos vacios", HEIGHT);
      }
    }//GEN-LAST:event_jbtnAgregarActionPerformed
 public void Actualizartabla()   
    {
    try {
       
        String sql = "SELECT mob_codigo , mob_nombre ,mob_precio FROM mobiliario ORDER BY mob_codigo";
        PreparedStatement ps = con.prepareStatement( sql );
        ResultSet rs = ps.executeQuery();
        datos.removeAllElements();
        while (rs.next()){
                int    ID      = rs.getInt     ( "mob_codigo" );
                String nombre = rs.getString  ( "mob_nombre" );
                String precio = rs.getString  ( "mob_precio" );
        fila = new Vector ();
        fila.add( ID );
        fila.add( nombre );
        fila.add(precio);
        
        datos.add( fila );
        }
        modelo = new DefaultTableModel(datos, columnas);
        jtableUsuarios.setModel(modelo);
    } catch (Exception ex) {System.out.println(ex);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Mobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Mobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Mobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Mobiliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Mobiliario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JButton jbtnRegresar;
    private javax.swing.JTable jtableUsuarios;
    private javax.swing.JTextField jtxfNombre;
    private javax.swing.JTextField jtxfprecio;
    private javax.swing.JLabel labelFonfo;
    // End of variables declaration//GEN-END:variables
}
